HW#9 Advanced Flask ready for review
Andrii-Kalyniuk/common pull request #12
Opened 2019-11-06 23:19 UTC by Andrii-Kalyniuk

2019-11-06 23:20 UTC, Andrii-Kalyniuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [#9 "H/W Advanced Flask". Kalyniuk Andrii](https://trello.com/c/cVuucSfd/195-9-h-w-advanced-flask-kalyniuk-andrii)

2019-11-08 20:55 UTC, yuriimchg requested changes
привіт
переглянув дз
аппка виглядає дуже круто, але є декілька моментів, які треба виправити:
1. Якщо додати супермаркет без картинки, то замість картинки отримується такий текст. Краще, нехай буде якась дефолтна картинка або якийсь текст-заглушка.
![image](https://user-images.githubusercontent.com/33547678/68509484-aaea4680-0279-11ea-99ae-1fc92468594e.png)
2. Я можу зробити для продуктів від'ємну ціну, але вона не може бути `float`. Краще, коли навпаки :wink: 
3. 
мінімально свариться лінтер
```
./flask_advanced/database.py:1:8: W292 no newline at end of file
./flask_advanced/products/products.py:1:80: E501 line too long (81 > 79 characters)
./flask_intro/app.py:1:1: F401 'flask.url_for' imported but unused

```

3. Картинки, які додавалися не з  static, не відображаються

2019-11-08 20:55 UTC, yuriimchg commented on flask_hw/flask_advanced/home/templates/error_404.html
> +</html>
No newline at the end of file

2019-11-08 20:55 UTC, yuriimchg commented on flask_hw/flask_advanced/products/templates/add_product.html
> +{% endblock %}
newline

2019-11-08 21:01 UTC, yuriimchg commented
_+_ коментар
в тебе є хендлер бази даних, але самої бд немає

2019-11-09 17:03 UTC, Andrii-Kalyniuk commented on flask_hw/flask_advanced/home/templates/error_404.html
> +</html>
виправив

2019-11-09 17:04 UTC, Andrii-Kalyniuk commented on flask_hw/flask_advanced/products/templates/add_product.html
> +{% endblock %}
виправив

2019-11-11 22:58 UTC, yuriimchg approved these changes
переглянув
дуже класне домашнє

ще зауваження: фільтрування по іменах чутливе до регістру, це не дуже добре

2019-11-11 23:19 UTC, merged