HW#10 "Flask RESTful" ready for review
Andrii-Kalyniuk/common pull request #13
Opened 2019-11-14 01:59 UTC by Andrii-Kalyniuk

HW#10 "Flask RESTful" ready for review

2019-11-14 02:00 UTC, Andrii-Kalyniuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#10 "Flask RESTful API". Kalyniuk Andrii](https://trello.com/c/O6Ynj5g4/216-hw10-flask-restful-api-kalyniuk-andrii)

2019-11-23 02:11 UTC, yuriimchg requested changes

2019-11-23 02:11 UTC, yuriimchg commented on flask_hw/flask_rest/config.py
> +    else:
це можна гарно загорнути в словник)

2019-11-23 02:11 UTC, yuriimchg commented on flask_hw/flask_rest/room/rooms.py
> +        logging.debug(args)
лайк за логування)

2019-11-23 02:11 UTC, yuriimchg commented on flask_hw/flask_rest/room/rooms.py
> +            room = list(filter(lambda r: id_ == r.id, DB['rooms']))
фільтрувати по id, звичайно, круто
але в конкретному випадку, напевно, все ж краще по номеру

2019-11-23 02:11 UTC, yuriimchg commented on flask_hw/flask_rest/room/rooms.py
> +        data = request.json
не можу створити нову кімнату:
POST 127.0.0.1:5000/api/v0.1/rooms?price=98&status=occ&level=1&number=102

2019-11-23 02:11 UTC, yuriimchg commented on flask_hw/flask_rest/room/rooms.py
> +        if id_:
аналогічно не можу змінити наявну кімнату - щось не ок з пошуком по id

2019-11-25 21:52 UTC, Andrii-Kalyniuk commented on flask_hw/flask_rest/config.py
> +    else:
зробив

2019-11-25 21:53 UTC, Andrii-Kalyniuk commented on flask_hw/flask_rest/room/rooms.py
> +            room = list(filter(lambda r: id_ == r.id, DB['rooms']))
Прибрав з моделей UUID, тепер пошук працює по номеру

2019-11-25 22:03 UTC, Andrii-Kalyniuk commented on flask_hw/flask_rest/room/rooms.py
> +        data = request.json
![Screenshot from 2019-11-25 23-54-58](https://user-images.githubusercontent.com/39514114/69581906-0fc6d000-0fe0-11ea-8cf4-787ba3af7e26.png)

Запрацювало після вилучення з моделі UUID

2019-11-25 22:04 UTC, Andrii-Kalyniuk commented on flask_hw/flask_rest/room/rooms.py
> +        if id_:
![Screenshot from 2019-11-25 23-57-39](https://user-images.githubusercontent.com/39514114/69581981-3b49ba80-0fe0-11ea-8740-da219f9c2053.png)

Виправив

2019-11-27 22:53 UTC, yuriimchg requested changes
Перевірив дз, код виглядає дуже гарно, чисто і акуратно. Дуже багато високорівневого функціоналу :+1: Ну і без пошуку по `id` все знаходиться максимально просто. 

З нехорошого:
* 404 помилка, яка не отримана переадресацією звідкись, загорнута в html. Думаю, варто зробити свою;
* Також дуже мінімально свариться лінтер.
* Ще я дивився в основному на Rooms, але впевнений, що для Tenants і Staff зауваження будуть схожими.

`GET`:
127.0.0.1:5000/api/v0.1/rooms  :heavy_check_mark: 
127.0.0.1:5000/api/v0.1/rooms/42 :heavy_check_mark: # room exists
127.0.0.1:5000/api/v0.1/rooms/43 :heavy_check_mark: # room does not exist
127.0.0.1:5000/api/v0.1/rooms?status=available :heavy_check_mark: 
127.0.0.1:5000/api/v0.1/rooms?status=closed :heavy_check_mark: 
127.0.0.1:5000/api/v0.1/rooms?status=broken :heavy_check_mark: # Empty list
Є фільтрація по номеру кімнати :heavy_check_mark: 
`POST`:
Немає фільтрації по від'ємній ціні / від'ємному поверху / від'ємному номеру кімнати. :x: 
Зато тішить, що ціну і номер не прийняло текстові :heavy_check_mark: 
І взагалі дуже круто, що відображаються всі параметри, які не підійшли / відсутні. Це мегазручно :heavy_check_mark: 
`PUT`:
Метод працює і це дуже добре :+1: 
Зауваження таке саме, що й для POST.
Також, на мою думку, номер не варто перезаписувати на новий, оскільки виходить, що PUT == DELETE + POST. Але конкретно в цьому випадку можна залишити як є.
Також в PUT бажано додавати більше тексту в повідомлення, яке повертається. Далеко не всі запити (особливо в цьому дз) є успішними :wink:

2019-11-27 22:53 UTC, yuriimchg commented on flask_hw/flask_rest/room/room_parsers.py
> +    if req in ['POST', 'PUT']:
дуже цікава ідея об'єднати Post, Put методи)

2019-11-27 22:53 UTC, yuriimchg commented on flask_hw/flask_rest/room/rooms.py
> +        return {"message": "room number not specified"}, 400
це приклад дуже хорошого коду :+1:

2019-11-28 21:24 UTC, Andrii-Kalyniuk commented on flask_hw/flask_rest/room/room_parsers.py
> +    if req in ['POST', 'PUT']:
![2019-11-28](https://user-images.githubusercontent.com/39514114/69832206-bf48b000-1235-11ea-9a6a-ff699866ab18.png)
Дякую за добре слово :) та зауваження.
Здається, що все виправив

2019-11-30 12:07 UTC, dimigor approved these changes

2019-12-30 23:26 UTC, merged